server:
  port: 9001
spring:
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    host: www.azhu.work
    port: 16379
    password:
  session:
    store-type: redis

netty:
  port: 8070
  isDistributed: true